// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'citizen_data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CitizenData _$CitizenDataFromJson(Map<String, dynamic> json) => CitizenData(
      batchid: json['batchid'] as String?,
      birthcountry: json['birthcountry'] as String?,
      birthdate: json['birthdate'] as String?,
      birthlga: json['birthlga'] as String?,
      birthstate: json['birthstate'] as String?,
      cardstatus: json['cardstatus'] as String?,
      centralID: json['centralID'] as String?,
      documentno: json['documentno'] as String?,
      educationallevel: json['educationallevel'] as String?,
      email: json['email'] as String?,
      employmentStatus: json['emplymentstatus'] as String?,
      firstname: json['firstname'] as String?,
      gender: json['gender'] as String?,
      heigth: (json['heigth'] as num?)?.toInt(),
      maidenname: json['maidenname'] as String?,
      maritalstatus: json['maritalstatus'] as String?,
      middlename: json['middlename'] as String?,
      nin: json['nin'] as String?,
      nok_address1: json['nok_address1'] as String?,
      nok_address2: json['nok_address2'] as String?,
      nok_firstname: json['nok_firstname'] as String?,
      nok_lga: json['nok_lga'] as String?,
      nok_middlename: json['nok_middlename'] as String?,
      nok_postalcode: json['nok_postalcode'] as String?,
      nok_state: json['nok_state'] as String?,
      nok_surname: json['nok_surname'] as String?,
      nok_town: json['nok_town'] as String?,
      nspokenlang: json['nspokenlang'] as String?,
      ospokenlang: json['ospokenlang'] as String?,
      othername: json['othername'] as String?,
      pfirstname: json['pfirstname'] as String?,
      photo: json['photo'] as String?,
      pmiddlename: json['pmiddlename'] as String?,
      profession: json['profession'] as String?,
      psurname: json['psurname'] as String?,
      religion: json['religion'] as String?,
      residence_AdressLine1: json['residence_AdressLine1'] as String?,
      residence_AdressLine2: json['residence_AdressLine2'] as String?,
      residence_Town: json['residence_Town'] as String?,
      residence_lga: json['residence_lga'] as String?,
      residence_postalcode: json['residence_postalcode'] as String?,
      residence_state: json['residence_state'] as String?,
      residencestatus: json['residencestatus'] as String?,
      self_origin_lga: json['self_origin_lga'] as String?,
      self_origin_place: json['self_origin_place'] as String?,
      self_origin_state: json['self_origin_state'] as String?,
      signature: json['signature'] as String?,
      surname: json['surname'] as String?,
      telephoneno: json['telephoneno'] as String?,
      title: json['title'] as String?,
      trackingId: json['trackingId'] as String?,
      CitizenID: json['CitizenID'] as String?,
      HashedID: json['HashedID'] as String?,
    );

Map<String, dynamic> _$CitizenDataToJson(CitizenData instance) =>
    <String, dynamic>{
      'batchid': instance.batchid,
      'birthcountry': instance.birthcountry,
      'birthdate': instance.birthdate,
      'birthlga': instance.birthlga,
      'birthstate': instance.birthstate,
      'cardstatus': instance.cardstatus,
      'centralID': instance.centralID,
      'documentno': instance.documentno,
      'educationallevel': instance.educationallevel,
      'email': instance.email,
      'emplymentstatus': instance.employmentStatus,
      'firstname': instance.firstname,
      'gender': instance.gender,
      'heigth': instance.heigth,
      'maidenname': instance.maidenname,
      'maritalstatus': instance.maritalstatus,
      'middlename': instance.middlename,
      'nin': instance.nin,
      'nok_address1': instance.nok_address1,
      'nok_address2': instance.nok_address2,
      'nok_firstname': instance.nok_firstname,
      'nok_lga': instance.nok_lga,
      'nok_middlename': instance.nok_middlename,
      'nok_postalcode': instance.nok_postalcode,
      'nok_state': instance.nok_state,
      'nok_surname': instance.nok_surname,
      'nok_town': instance.nok_town,
      'nspokenlang': instance.nspokenlang,
      'ospokenlang': instance.ospokenlang,
      'othername': instance.othername,
      'pfirstname': instance.pfirstname,
      'photo': instance.photo,
      'pmiddlename': instance.pmiddlename,
      'profession': instance.profession,
      'psurname': instance.psurname,
      'religion': instance.religion,
      'residence_AdressLine1': instance.residence_AdressLine1,
      'residence_AdressLine2': instance.residence_AdressLine2,
      'residence_Town': instance.residence_Town,
      'residence_lga': instance.residence_lga,
      'residence_postalcode': instance.residence_postalcode,
      'residence_state': instance.residence_state,
      'residencestatus': instance.residencestatus,
      'self_origin_lga': instance.self_origin_lga,
      'self_origin_place': instance.self_origin_place,
      'self_origin_state': instance.self_origin_state,
      'signature': instance.signature,
      'surname': instance.surname,
      'telephoneno': instance.telephoneno,
      'title': instance.title,
      'trackingId': instance.trackingId,
      'CitizenID': instance.CitizenID,
      'HashedID': instance.HashedID,
    };
